#!/bin/sh
#clear
#echo ""

# This thing will start the application, starts the script called:
# build/install/myNodePubSub/bin/<projectName>/<projectName>

# made by Jaroslav Vitku


# this is where I am (and all things to copy)
BASEDIR=$(dirname $0)

echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 

# get the name of parent folder (project)
NAME=${PWD##*/}
# go to the subfulder where the launch script is installed 
cd build/install/$NAME/bin/

echo "eeeeeeeeeeeeeeeeeeeeee runing this: " $NAME

./$NAME vivae.ros.simulatorControlsServer.ControlsServer



