#!/bin/sh
#
# Almost universal launcher of appllication installed by means of Gradle.
#
# If the installation files are found (/build/install), the aplication is started, 
# if not, the applicatoion is installed from source and started.
#
# Should work with any gradle project

# @author Jaroslav Vitku

usage()
{
	echo ""
	echo "This script launches the ViVae simulaiton server. "
	echo "Before starting the server, lauch your preffered roscore (jroscore)"
	echo "The simulation server will listen to requests for simulaiton received over the ROS network."
	echo "These messages (service/client type) can be found under vivae/ros/vivae/srv"
	echo ""
}


##################################################### Parse command line
BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # we are here

OPTIND=1        # Reset in case getopts has been used previously in the shell.
while getopts "help?:" opt; do
    case "$opt" in
    h|\?|help)
        usage
        exit 0
        ;;
    esac
done

shift $((OPTIND-1))
[ "$1" = "--" ] && shift


##################################################### Start the project
NAME=${PWD##*/}         # project name (paren folder)
BASEDIR=$(dirname $0)   # my directory

# if no installation found, then install it
if [ ! -d "build/install/$NAME/bin/" ]; then
    echo "No installation found, installing from source.."
    ./gradlew installApp
    echo "\nInstalled\n"
fi

echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Starting Vivae SimulationServer NOW"  
cd build/install/$NAME/bin/

./$NAME vivae.ros.simulator.server.SimulatorServer



